# MongoDB connection properties
spring.data.mongodb.database=${env.MONGO_DATABASE}
spring.data.mongodb.uri=${env.MONGO_URI}
mongodb.collection.user-account-data=${env.MONGO_COLLECTION_USER}
mongodb.collection.verification-code=${env.MONGO_COLLECTION_VERIFICATION_CODE}
mongodb.collection.verification-link=${env.MONGO_COLLECTION_VERIFICATION_LINK}
mongodb.collection.api-keys=${env.MONGO_COLLECTION_API_KEYS}
spring.data.mongodb.auto-index-creation=true


# Thymeleaf configuration
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.web.resources.static-locations=classpath:/static/


# SMTP Gmail
spring.mail.host=${env.SPRING_MAIL_HOST}
spring.mail.port=${env.SPRING_MAIL_PORT}
spring.mail.username=${env.SPRING_MAIL_USERNAME}
spring.mail.password=${env.SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=${env.SMTP_AUTH}
spring.mail.properties.mail.smtp.starttls.enable=${env.SMTP_STARTTLS_ENABLE}


# Redis connection properties
spring.data.redis.host=${env.SPRING_REDIS_HOST}
spring.data.redis.port=${env.SPRING_REDIS_PORT}
spring.data.redis.password=${env.SPRING_REDIS_PASSWORD}
server.servlet.session.timeout=${env.SESSION_EXPIRATION_DEFAULT}


# Verification Link
link.change-password.path=/welcome/change-password?id=
link.create-account.path=/create_account.html?id=


# server port of your frontend
server.front-end.port=8000
server.front-end.base-url=http://localhost:${server.front-end.port}


# server port spring boot
server.port=8080
server.port.base-url=http://localhost:${server.port}


# CORS for REST
cors.allowed-origins=http://localhost:8000,http://localhost:3000
cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
cors.allowed-headers=*


