package john.LOGIN_SYSTEM.common.response;

import lombok.Getter;

@Getter
public enum ResponseType {
    // Error
    SIGNUP_ERROR, LOGIN_ERROR, RESET_PASSWORD_ERROR, VERIFICATION_ERROR,
    // Success
    SIGNUP_SUCCESS, LOGIN_SUCCESS, RESET_PASSWORD_SUCCESS, VERIFICATION_SUCCESS,
    // Exception
    SIGNUP_EXCEPTION, LOGIN_EXCEPTION, RESET_PASSWORD_EXCEPTION, VERIFICATION_EXCEPTION,
    // Unknown
    VERIFICATION_SENT_UNKNOWN,


    // Status
    ACCOUNT_RESTRICTED, ACCOUNT_BANNED, ACCOUNT_VALID,
    SIGNUP_PENDING,
    LINK_GENERATED, LINK_DELETED, LINK_EXPIRED,
    VERIFICATION_CODE_GENERATED, VERIFICATION_CODE_DELETED, VERIFICATION_CODE_EXPIRED, VERIFICATION_CODE_NOT_FOUND,
    REDIS_SESSION_OFFLINE,
    EXIT_APPLICATION,
    ACTION_UNAUTHORIZED,

    // Data Status
    ACCOUNT_EXIST, ACCOUNT_NOT_EXIST,

    // Email Status
    EMAIL_VERIFICATION_CODE_SUCCESS, EMAIL_VERIFICATION_LINK_SUCCESS, EMAIL_CHANGE_PASSWORD_SUCCESS,

    // Link Status
    CHANGE_PASSWORD_LINK_ACCESSED, CHANGE_PASSWORD_LINK_EXPIRED
}
